name:  Run tests

on: [push, pull_request, workflow_dispatch]
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3        
      - name: Unity - Test runner
        uses: game-ci/unity-test-runner@v2.1.1
        
